name: Crear Issues Iniciales Automáticamente

on:
  push:
    branches:
      - main

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Crear Issue Semana 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Semana 1: Definición del alcance y arquitectura","body":"Definir el alcance del proyecto, arquitectura y distribución de tareas."}'

      - name: Crear Issue Semana 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Semana 2: Implementación del crawler y extracción de datos","body":"Desarrollar el módulo crawler.py para extracción de eventos y validación."}'

      - name: Crear Issue Semana 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Semana 3: Normalización y procesamiento de eventos","body":"Construcción del módulo procesamiento.py para estandarizar eventos."}'

      - name: Crear Issue Semana 4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Semana 4: Generación de embeddings y búsqueda semántica","body":"Desarrollar embedding.py para vectorización y búsqueda eficiente."}'

      - name: Crear Issue Semana 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Semana 5: Construcción y uso del grafo de conocimiento","body":"Implementar grafo para relaciones y recomendaciones avanzadas."}'

      - name: Crear Issue Semana 6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Semana 6: Interfaz de usuario con Streamlit","body":"Desarrollar visual.py para UI interactiva con filtros y agendas."}'

      - name: Crear Issue Semana 7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Semana 7: Optimización y mejoras finales","body":"Refinar motor de recomendaciones, gestión de sesiones y documentación."}'

      - name: Crear Issue Semana 8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Semana 8: Preparación para entrega y presentación","body":"Redacción del README, reporte y preparación de la presentación final."}'
